version: "3"

services:
  php-apache:
    image: my-php-apache:test
    container_name: php-apache
    ports:
      - "8080:80"
    volumes:
      - /home/api-project/api-jwt:/var/www/html
    depends_on:
      - mysql
    networks:
      - my-net
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: myDB
    volumes:
      - /home/api-project/db:/var/lib/mysql
      - /home/api-project:/home
    networks:
      - my-net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    links:
      - "mysql:db"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge